FROM solr:9.0.0
WORKDIR /opt/solr-9.0.0
# RUN apt-get update && \
#     apt-get -y install sudo
# RUN echo "solr:solr" | chpasswd && adduser solr sudo
# USER solr
# CMD [ "sh", "-c", "sleep infinity" ]